builds:
  - main: ./main.go
    id: 'gtp'
    binary: gtp
  - goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
archives:
  - id: binary
    format: binary
    name_template: gtp
